version: '3.9'

services:
  postgres:
    container_name: in-orbit-pg
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: inorbit